name: qr3
description: "qr"



version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  simple_barcode_scanner: ^0.2.4


  mobile_scanner: ^6.0.2
  qr_mobile_vision: ^5.0.2
  persistent_bottom_nav_bar: ^6.2.1
  get: ^4.6.6
  fluttertoast: ^8.2.8
  intl_utils: ^2.8.7
  pretty_qr_code: ^3.3.0
  image_picker: ^1.1.2
  simple_image_cropper: ^1.0.0
  image_cropper: ^8.0.2
  zxing2: ^0.2.3
  image: ^4.3.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  share_plus: ^10.1.2
  intl: ^0.19.0
  device_calendar: ^4.3.3
  add_2_calendar: ^3.0.1
  flutter_form_builder: ^9.5.0
  geolocator: ^13.0.2
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2
  icons_launcher: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/qr.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:


  uses-material-design: true


  assets:
    - assets/strings/strings.json
    - assets/images/

flutter_native_splash:
  color: "#ffffff" # Color de fondo del splash
  image: assets/images/qr.png # Ruta de la imagen del logo
  android: true # Habilitar para Android
  android_12:
    image: assets/images/qr.png # Ruta de la imagen del logo

